[package]
name = "datafusion_util"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "Datafusion utilities"

[dependencies]
datafusion = { path = "../datafusion" }
futures = "0.3"
tokio = { version = "1.13", features = ["macros"] }
tokio-stream = "0.1.8"
