[package]
name = "mutable_batch"
version = "0.1.0"
edition = "2021"
description = "A mutable arrow RecordBatch"

[dependencies]
arrow = { version = "6.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
chrono = "0.4"
data_types = { path = "../data_types" }
schema = { path = "../schema" }
snafu = "0.6"
trace = { path = "../trace" }
time = { path = "../time" }
hashbrown = "0.11"
itertools = "0.10"

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
rand = "0.8"
