[package]
name = "tracker"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2021"
description = "Utilities for tracking resource utilisation within IOx"

[dependencies]

futures = "0.3"
hashbrown = "0.11"
lock_api = "0.4.4"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.11.2"
pin-project = "1.0"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "time"] }
tokio-util = { version = "0.6.9" }

[dev-dependencies]
# Need the multi-threaded executor for testing
tokio = { version = "1.13", features = ["macros", "time", "rt-multi-thread"] }
