[package]
name = "iox_object_store"
version = "0.1.0"
edition = "2021"
description = "IOx-specific semantics wrapping the general-purpose object store crate"

[dependencies]
bytes = "1.0"
chrono = "0.4"
data_types = { path = "../data_types" }
futures = "0.3"
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
snafu = "0.6"
tokio = { version = "1.13", features = ["macros", "time"] }
tokio-stream = "0.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
